spring:
  application:
    name: user

  config:
    import: classpath:nacos.yml

  datasource:
    url: jdbc:mysql://localhost:3306/ai_helper?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    database: mysql
    database-platform: mysql
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
    generate-ddl: false

server:
  port: 8083